### ISSUE TITLE
Snap should compile .pyc

### ISSUE THREAD

**Issue by sparkiegeek** [Roadmaster/surl#17]
$ snap run --strace surl --help 2>&1 | grep -c EROFS
    243

surl should compile PYCs when building the snap to avoid retrying to compile the bytecode over and over again

**Comment by cprov** [comment]
@sparkiegeek How ? I found https://bugs.launchpad.net/snapcraft/+bug/1758958 but it's disappointing

**Comment by Roadmaster** [comment]
brand spanking new build of surl passes this (admittedly arcane, I don't even know what we're doing here) test.
```
$ snap run --strace surl --help 2>&1 | grep -c EROFS
0
```
closing :)
